rules:
  # We don't care about non escaped PDO string as we need to provide table and column names from variables, unescaped
  doctrine.database_query_contains_string_and_variable_concatenation:
    enabled: true