databases:
  connections:
    - dsn: "sqlite::memory:"
      name: database1
      engine: sqlite
    - dsn: "sqlite::memory:"
      name: database2
      engine: sqlite

missingcompressiondetect:
relcheck:
uniqueintegritycheck:
fragmentationcheck:
analyzetablecheck:

filecheck:
  enable_remotes: true
  mapping:
    - tbl_simulation_document: "/var/www/mywebsite/web/uploads/simulationDocuments/LOA/{simulation_id}/{type_document_id.document_type_libelle_court}/{document}"

dataintegritycheck:
  mapping:
    - gac_ref_ca: 7f72049b1b7ea2e3e2cb1db6abf46bf1d1f1f2ef

schemaintegritycheck:
  allow_extras: true
  ignore:
    - rep_*
  mapping:
    - gac_ref_ca: 7f72049b1b7ea2e3e2cb1db6abf46bf1d1f1f2ef

missingkeydetect:
  threshold: 0.3
  patterns:
    - "_id$"